services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ita-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_EVENTS_API_URL: http://events:8080
      NEXT_PUBLIC_APPLICATIONS_API_URL: http://applications:8081
      NEXT_PUBLIC_USERS_API_URL: http://users:8082
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
