import type { Application, Event, User } from "@/lib/types/domain";

export const MOCK_EVENTS: Event[] = [
  {
    id: "pulse-summit-2026",
    title: "Pulse Summit 2026",
    tagline: "Where product teams meet ambitious ideas.",
    description:
      "A one-day summit focused on product strategy, growth loops, and practical workshops for founders and builders.",
    date: "2026-05-14",
    time: "09:00",
    location: "Ljubljana Innovation Hub",
    mode: "In Person",
    category: "Business",
    capacity: 320,
    registered: 214,
    priceLabel: "39 EUR",
    host: "ITA Collective",
    coverGradient: "from-[#ff9966] to-[#ff5e62]",
    featured: true,
  },
  {
    id: "midnight-design-lab",
    title: "Midnight Design Lab",
    tagline: "Build bold interfaces under pressure.",
    description:
      "An experimental design sprint where teams prototype event experiences in six hours, mentored by senior designers.",
    date: "2026-06-02",
    time: "18:30",
    location: "Kino Siska Studio",
    mode: "Hybrid",
    category: "Workshop",
    capacity: 80,
    registered: 57,
    priceLabel: "Free",
    host: "Pixel Forge",
    coverGradient: "from-[#36d1dc] to-[#5b86e5]",
    featured: true,
  },
  {
    id: "future-of-ai-meetup",
    title: "Future of AI Meetup",
    tagline: "Real-world AI stories from local teams.",
    description:
      "Talks and panel on shipping AI features, model reliability, and product ethics from Balkan startup teams.",
    date: "2026-04-22",
    time: "17:00",
    location: "Maribor Digital Center",
    mode: "In Person",
    category: "Tech",
    capacity: 180,
    registered: 141,
    priceLabel: "12 EUR",
    host: "Slovenia AI Circle",
    coverGradient: "from-[#1fa2ff] to-[#12d8fa]",
  },
  {
    id: "open-city-culture-night",
    title: "Open City Culture Night",
    tagline: "Music, stories, and local creators.",
    description:
      "An evening event celebrating independent culture projects with live sessions, talks, and community booths.",
    date: "2026-07-11",
    time: "19:30",
    location: "Trg Republike",
    mode: "In Person",
    category: "Culture",
    capacity: 500,
    registered: 366,
    priceLabel: "Free",
    host: "Open City Initiative",
    coverGradient: "from-[#f6d365] to-[#fda085]",
  },
  {
    id: "community-growth-clinic",
    title: "Community Growth Clinic",
    tagline: "From first members to healthy rituals.",
    description:
      "Hands-on clinic for community managers and event organizers focused on retention, engagement, and automation.",
    date: "2026-08-03",
    time: "10:00",
    location: "Online",
    mode: "Online",
    category: "Community",
    capacity: 220,
    registered: 98,
    priceLabel: "25 EUR",
    host: "Growth Orbit",
    coverGradient: "from-[#43cea2] to-[#185a9d]",
  },
];

export const MOCK_USER: User = {
  id: "user-001",
  name: "Mila Novak",
  role: "Organizer",
  email: "mila.novak@ita.local",
  city: "Ljubljana",
  avatarInitials: "MN",
};

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: "app-1",
    userId: "user-001",
    eventId: "pulse-summit-2026",
    status: "Confirmed",
    createdAt: "2026-03-12",
  },
  {
    id: "app-2",
    userId: "user-001",
    eventId: "future-of-ai-meetup",
    status: "Pending",
    createdAt: "2026-03-15",
  },
  {
    id: "app-3",
    userId: "user-001",
    eventId: "community-growth-clinic",
    status: "Waitlisted",
    createdAt: "2026-03-14",
  },
];
